import { createProvider } from "../factory";

export const colombiaProviders = [
  createProvider({
    id: "co-1",
    name: "Medellín Rhinoplasty Institute",
    slug: "medellin-rhinoplasty-institute",
    country: "Colombia",
    city: "Medellín",
    address: "El Poblado, Cra. 43A #1-50, Medellín, Antioquia",
    description: "World-renowned rhinoplasty center in the aesthetic surgery capital of Latin America.",
    accreditations: ["JCI", "ISO 9001", "Colombia Medical Tourism"],
    procedures: ["Rhinoplasty", "Facelift"],
    procedurePrices: [
      { name: "Rhinoplasty", priceUsd: 2800 },
      { name: "Revision Rhinoplasty", priceUsd: 3600 },
      { name: "Facelift", priceUsd: 4200 },
    ],
    lat: 6.2088,
    lng: -75.5676,
    contactEmail: "info@medellin-rhino.co",
    contactPhone: "+57 604 444 1234",
    rating: 4.9,
    reviewCount: 1234,
  }),
  createProvider({
    id: "co-2",
    name: "Bogotá Cosmetic Surgery Hospital",
    slug: "bogota-cosmetic-surgery-hospital",
    country: "Colombia",
    city: "Bogotá",
    address: "Calle 127 #15-60, Usaquén, Bogotá",
    description: "Full-service cosmetic hospital with body contouring and facial surgery departments.",
    accreditations: ["JCI", "ISO 9001"],
    procedures: ["Rhinoplasty", "Liposuction", "Breast Augmentation", "Tummy Tuck"],
    lat: 4.711,
    lng: -74.0324,
    contactEmail: "cosmetic@bogota-hospital.co",
    contactPhone: "+57 601 234 5678",
    rating: 4.8,
    reviewCount: 567,
  }),
  createProvider({
    id: "co-3",
    name: "Cali Liposuction Center",
    slug: "cali-liposuction-center",
    country: "Colombia",
    city: "Cali",
    address: "Granada, Cali, Valle del Cauca",
    description: "Body sculpting specialists with VASER liposuction expertise.",
    accreditations: ["ISO 9001", "Colombia Medical Tourism"],
    procedures: ["Liposuction", "Tummy Tuck", "Breast Augmentation"],
    lat: 3.4516,
    lng: -76.532,
    contactEmail: "body@cali-lipo.co",
    contactPhone: "+57 602 345 6789",
    rating: 4.7,
    reviewCount: 345,
  }),
  createProvider({
    id: "co-4",
    name: "Medellín Dental Tourism Clinic",
    slug: "medellin-dental-tourism-clinic",
    country: "Colombia",
    city: "Medellín",
    address: "Laureles, Circular 3 #71-04, Medellín",
    description: "Modern dental clinic with implant and veneer packages for international patients.",
    accreditations: ["ISO 9001", "ADA Member"],
    procedures: ["Dental Implants", "Veneers", "All-on-4", "Dental Crowns"],
    lat: 6.2442,
    lng: -75.5812,
    contactEmail: "dental@medellin-tourism.co",
    contactPhone: "+57 604 567 8901",
    rating: 4.8,
    reviewCount: 289,
  }),
  createProvider({
    id: "co-5",
    name: "Cartagena Aesthetic Retreat",
    slug: "cartagena-aesthetic-retreat",
    country: "Colombia",
    city: "Cartagena",
    address: "Bocagrande, Carrera 3 #8-129, Cartagena",
    description: "Boutique aesthetic clinic in a historic coastal city with luxury recovery hotels.",
    accreditations: ["ISO 9001"],
    procedures: ["Rhinoplasty", "Facelift", "Liposuction"],
    lat: 10.3997,
    lng: -75.5526,
    contactEmail: "retreat@cartagena-aesthetic.co",
    contactPhone: "+57 605 678 9012",
    rating: 4.6,
    reviewCount: 178,
  }),
  createProvider({
    id: "co-6",
    name: "Bogotá Fertility Center",
    slug: "bogota-fertility-center",
    country: "Colombia",
    city: "Bogotá",
    address: "Chicó Norte, Carrera 9 #115-30, Bogotá",
    description: "IVF center with donor egg programs and genetic testing services.",
    accreditations: ["JCI", "ISO 15189"],
    procedures: ["IVF", "Egg Freezing"],
    lat: 4.6937,
    lng: -74.0456,
    contactEmail: "ivf@bogota-fertility.co",
    contactPhone: "+57 601 789 0123",
    rating: 4.8,
    reviewCount: 412,
  }),
  createProvider({
    id: "co-7",
    name: "Medellín Bariatric Specialists",
    slug: "medellin-bariatric-specialists",
    country: "Colombia",
    city: "Medellín",
    address: "Envigado, Carrera 43A #27 Sur-145, Medellín",
    description: "Metabolic surgery center with comprehensive post-operative support.",
    accreditations: ["JCI", "ISO 9001"],
    procedures: ["Gastric Sleeve", "Gastric Bypass"],
    lat: 6.1696,
    lng: -75.5784,
    contactEmail: "bariatric@medellin-specialists.co",
    contactPhone: "+57 604 890 1234",
    rating: 4.7,
    reviewCount: 234,
  }),
  createProvider({
    id: "co-8",
    name: "Barranquilla Hair Transplant Clinic",
    slug: "barranquilla-hair-transplant-clinic",
    country: "Colombia",
    city: "Barranquilla",
    address: "Alto Prado, Carrera 52 #74-152, Barranquilla",
    description: "FUE hair restoration with Caribbean coast recovery packages.",
    accreditations: ["ISHRS Member", "ISO 9001"],
    procedures: ["Hair Transplant"],
    lat: 10.9998,
    lng: -74.8044,
    contactEmail: "hair@barranquilla-clinic.co",
    contactPhone: "+57 605 901 2345",
    rating: 4.5,
    reviewCount: 156,
  }),
  createProvider({
    id: "co-9",
    name: "Bogotá Orthopedic Institute",
    slug: "bogota-orthopedic-institute",
    country: "Colombia",
    city: "Bogotá",
    address: "Chapinero, Calle 53 #13-27, Bogotá",
    description: "Joint replacement and sports medicine center with robotic surgery.",
    accreditations: ["JCI", "ISO 9001"],
    procedures: ["Knee Replacement", "Hip Replacement", "ACL Reconstruction"],
    lat: 4.6369,
    lng: -74.0849,
    contactEmail: "ortho@bogota-institute.co",
    contactPhone: "+57 601 012 3456",
    rating: 4.7,
    reviewCount: 198,
  }),
  createProvider({
    id: "co-10",
    name: "Medellín LASIK Vision Center",
    slug: "medellin-lasik-vision-center",
    country: "Colombia",
    city: "Medellín",
    address: "El Tesoro, Medellín, Antioquia",
    description: "Advanced refractive surgery with SMILE and LASIK options.",
    accreditations: ["ISO 9001", "AAO Member"],
    procedures: ["LASIK Eye Surgery", "Cataract Surgery"],
    lat: 6.1967,
    lng: -75.5569,
    contactEmail: "vision@medellin-lasik.co",
    contactPhone: "+57 604 123 4567",
    rating: 4.8,
    reviewCount: 167,
  }),
  createProvider({
    id: "co-11",
    name: "Pereira Spine Surgery Center",
    slug: "pereira-spine-surgery-center",
    country: "Colombia",
    city: "Pereira",
    address: "Calle 19 #12-20, Pereira, Risaralda",
    description: "Spine surgery specialists serving the coffee region of Colombia.",
    accreditations: ["ISO 9001"],
    procedures: ["Spine Surgery"],
    lat: 4.8133,
    lng: -75.6961,
    contactEmail: "spine@pereira-center.co",
    contactPhone: "+57 606 234 5678",
    rating: 4.6,
    reviewCount: 89,
  }),
];
