import { createProvider, pricesFor } from "../factory";

export const costaRicaProviders = [
  createProvider({
    id: "cr-1",
    name: "Costa Rica Dental & Wellness",
    slug: "costa-rica-dental-wellness",
    country: "Costa Rica",
    city: "San José",
    address: "Escazú Medical Center, San Rafael de Escazú, San José",
    description: "Boutique dental clinic offering implants, crowns, and holistic wellness packages.",
    accreditations: ["AAID", "ISO 9001", "Costa Rica Medical Tourism Board"],
    procedures: ["Dental Implants", "Dental Crowns", "Veneers"],
    procedurePrices: pricesFor(["Dental Implants", "Dental Crowns", "Veneers"], {
      "Dental Implants": 950,
      "Dental Crowns": 420,
      Veneers: 380,
    }),
    lat: 9.9187,
    lng: -84.1399,
    contactEmail: "smile@crwellness.co.cr",
    contactPhone: "+506 2222 3333",
    rating: 4.9,
    reviewCount: 278,
  }),
  createProvider({
    id: "cr-2",
    name: "Liberty Medical Costa Rica",
    slug: "liberty-medical-costa-rica",
    country: "Costa Rica",
    city: "Liberia",
    address: "Centro Comercial Plaza Real, Liberia, Guanacaste",
    description: "Gateway clinic near Liberia airport specializing in bariatric and orthopedic care.",
    accreditations: ["JCI", "Promed", "ISO 14001"],
    procedures: ["Gastric Sleeve", "Gastric Bypass", "Knee Replacement", "Hip Replacement"],
    lat: 10.635,
    lng: -85.4377,
    contactEmail: "info@libertymedical.cr",
    contactPhone: "+506 2666 4444",
    rating: 4.6,
    reviewCount: 156,
  }),
  createProvider({
    id: "cr-3",
    name: "San José Cosmetic Surgery Center",
    slug: "san-jose-cosmetic-surgery-center",
    country: "Costa Rica",
    city: "San José",
    address: "Barrio Escalante, San José 10105",
    description: "Board-certified plastic surgeons offering body and facial aesthetic procedures.",
    accreditations: ["Promed", "ISO 9001"],
    procedures: ["Tummy Tuck", "Liposuction", "Breast Augmentation"],
    lat: 9.9347,
    lng: -84.0658,
    contactEmail: "cosmetic@sj-center.cr",
    contactPhone: "+506 2234 5678",
    rating: 4.7,
    reviewCount: 189,
  }),
  createProvider({
    id: "cr-4",
    name: "Escazú Fertility Clinic",
    slug: "escazu-fertility-clinic",
    country: "Costa Rica",
    city: "Escazú",
    address: "Multiplaza Escazú, San Rafael, Escazú",
    description: "IVF center with high success rates and English-speaking embryologists.",
    accreditations: ["JCI", "Promed"],
    procedures: ["IVF", "Egg Freezing"],
    lat: 9.9326,
    lng: -84.1447,
    contactEmail: "fertility@escazu-clinic.cr",
    contactPhone: "+506 2289 0123",
    rating: 4.8,
    reviewCount: 234,
  }),
  createProvider({
    id: "cr-5",
    name: "Tamarindo Dental Implants",
    slug: "tamarindo-dental-implants",
    country: "Costa Rica",
    city: "Tamarindo",
    address: "Main Road, Tamarindo, Guanacaste",
    description: "Beach-town dental clinic popular with surfers and expats seeking affordable implants.",
    accreditations: ["AAID", "ISO 9001"],
    procedures: ["Dental Implants", "All-on-4", "Veneers"],
    lat: 10.2993,
    lng: -85.8371,
    contactEmail: "dental@tamarindo-implants.cr",
    contactPhone: "+506 2653 4567",
    rating: 4.8,
    reviewCount: 145,
  }),
  createProvider({
    id: "cr-6",
    name: "Cartago Orthopedic Institute",
    slug: "cartago-orthopedic-institute",
    country: "Costa Rica",
    city: "Cartago",
    address: "Avenida Central, Cartago 30101",
    description: "Joint replacement specialists with physical therapy recovery programs.",
    accreditations: ["JCI", "Promed"],
    procedures: ["Knee Replacement", "Hip Replacement", "ACL Reconstruction"],
    lat: 9.8644,
    lng: -83.9194,
    contactEmail: "ortho@cartago-institute.cr",
    contactPhone: "+506 2551 2345",
    rating: 4.6,
    reviewCount: 98,
  }),
  createProvider({
    id: "cr-7",
    name: "Manuel Antonio LASIK Center",
    slug: "manuel-antonio-lasik-center",
    country: "Costa Rica",
    city: "Quepos",
    address: "Quepos Town Center, Puntarenas",
    description: "Eye surgery center near Manuel Antonio National Park for medical tourism packages.",
    accreditations: ["ISO 9001"],
    procedures: ["LASIK Eye Surgery", "Cataract Surgery"],
    lat: 9.4311,
    lng: -84.1628,
    contactEmail: "vision@manuel-lasik.cr",
    contactPhone: "+506 2777 8901",
    rating: 4.7,
    reviewCount: 112,
  }),
  createProvider({
    id: "cr-8",
    name: "Heredia Bariatric Center",
    slug: "heredia-bariatric-center",
    country: "Costa Rica",
    city: "Heredia",
    address: "Paseo de las Flores, Heredia 40101",
    description: "Dedicated weight-loss surgery center with nutritionist support.",
    accreditations: ["Promed", "ISO 9001"],
    procedures: ["Gastric Sleeve", "Gastric Bypass"],
    lat: 9.9985,
    lng: -84.1165,
    contactEmail: "bariatric@heredia-center.cr",
    contactPhone: "+506 2260 3456",
    rating: 4.5,
    reviewCount: 167,
  }),
  createProvider({
    id: "cr-9",
    name: "Jaco Beach Hair Restoration",
    slug: "jaco-beach-hair-restoration",
    country: "Costa Rica",
    city: "Jacó",
    address: "Avenida Pastor Díaz, Jacó, Puntarenas",
    description: "Hair transplant clinic with beach recovery packages.",
    accreditations: ["ISHRS Member"],
    procedures: ["Hair Transplant"],
    lat: 9.6147,
    lng: -84.6284,
    contactEmail: "hair@jaco-restoration.cr",
    contactPhone: "+506 2643 5678",
    rating: 4.6,
    reviewCount: 89,
  }),
  createProvider({
    id: "cr-10",
    name: "Alajuela Spine Center",
    slug: "alajuela-spine-center",
    country: "Costa Rica",
    city: "Alajuela",
    address: "City Mall, Alajuela 20101",
    description: "Minimally invasive spine surgery near Juan Santamaría International Airport.",
    accreditations: ["JCI", "Promed"],
    procedures: ["Spine Surgery"],
    lat: 10.0162,
    lng: -84.2116,
    contactEmail: "spine@alajuela-center.cr",
    contactPhone: "+506 2436 7890",
    rating: 4.7,
    reviewCount: 76,
  }),
];
