import { createProvider, pricesFor } from "../factory";

export const indiaProviders = [
  createProvider({
    id: "in-1",
    name: "Apollo MedTour India",
    slug: "apollo-medtour-india",
    country: "India",
    city: "New Delhi",
    address: "Sarita Vihar, Delhi Mathura Road, New Delhi 110076",
    description: "Part of India's largest healthcare network, offering cardiac, orthopedic, and fertility procedures.",
    accreditations: ["JCI", "NABH", "NABL"],
    procedures: ["Cardiac Bypass", "Knee Replacement", "Spine Surgery", "IVF"],
    procedurePrices: pricesFor(
      ["Cardiac Bypass", "Knee Replacement", "Spine Surgery", "IVF"],
      { "Cardiac Bypass": 6500, "Knee Replacement": 5500, "Spine Surgery": 7200, IVF: 2800 }
    ),
    lat: 28.5355,
    lng: 77.291,
    contactEmail: "medtour@apolloindia.com",
    contactPhone: "+91 11 2692 5858",
    rating: 4.8,
    reviewCount: 1243,
  }),
  createProvider({
    id: "in-2",
    name: "Chennai Eye & Laser Center",
    slug: "chennai-eye-laser-center",
    country: "India",
    city: "Chennai",
    address: "21 Greams Road, Thousand Lights, Chennai 600006",
    description: "Specialized ophthalmology center performing LASIK, cataract, and retinal treatments.",
    accreditations: ["NABH", "ISO 9001", "AAO Member"],
    procedures: ["LASIK Eye Surgery", "Cataract Surgery"],
    procedurePrices: pricesFor(["LASIK Eye Surgery", "Cataract Surgery"], {
      "LASIK Eye Surgery": 800,
      "Cataract Surgery": 450,
    }),
    lat: 13.0569,
    lng: 80.2425,
    contactEmail: "appointments@chennaieye.in",
    contactPhone: "+91 44 2829 3333",
    rating: 4.9,
    reviewCount: 456,
  }),
  createProvider({
    id: "in-3",
    name: "Mumbai Cosmetic Surgery Hospital",
    slug: "mumbai-cosmetic-surgery-hospital",
    country: "India",
    city: "Mumbai",
    address: "Dr. E Borges Road, Parel, Mumbai 400012",
    description: "Premier aesthetic surgery department with rhinoplasty and body contouring specialists.",
    accreditations: ["NABH", "JCI"],
    procedures: ["Rhinoplasty", "Facelift", "Liposuction"],
    lat: 19.0047,
    lng: 72.8417,
    contactEmail: "cosmetic@mumbai-hospital.in",
    contactPhone: "+91 22 2410 2345",
    rating: 4.7,
    reviewCount: 389,
  }),
  createProvider({
    id: "in-4",
    name: "Bangalore Fertility & IVF Center",
    slug: "bangalore-fertility-ivf-center",
    country: "India",
    city: "Bangalore",
    address: "123 MG Road, Bangalore 560001",
    description: "High-volume IVF center with advanced embryology lab and genetic testing.",
    accreditations: ["NABH", "ISO 15189"],
    procedures: ["IVF", "Egg Freezing"],
    lat: 12.9758,
    lng: 77.6064,
    contactEmail: "ivf@bangalore-fertility.in",
    contactPhone: "+91 80 2345 6789",
    rating: 4.8,
    reviewCount: 678,
  }),
  createProvider({
    id: "in-5",
    name: "Hyderabad Dental Excellence",
    slug: "hyderabad-dental-excellence",
    country: "India",
    city: "Hyderabad",
    address: "Road No. 12, Banjara Hills, Hyderabad 500034",
    description: "Full-service dental hospital with implant and cosmetic dentistry departments.",
    accreditations: ["NABH", "ISO 9001"],
    procedures: ["Dental Implants", "All-on-4", "Veneers", "Dental Crowns"],
    lat: 17.4126,
    lng: 78.4344,
    contactEmail: "dental@hyderabad-excellence.in",
    contactPhone: "+91 40 2345 6789",
    rating: 4.7,
    reviewCount: 234,
  }),
  createProvider({
    id: "in-6",
    name: "Gurgaon Orthopedic Institute",
    slug: "gurgaon-orthopedic-institute",
    country: "India",
    city: "Gurgaon",
    address: "Sector 44, Gurgaon, Haryana 122003",
    description: "Robotic joint replacement and sports medicine center near Delhi airport.",
    accreditations: ["JCI", "NABH"],
    procedures: ["Knee Replacement", "Hip Replacement", "ACL Reconstruction"],
    lat: 28.4595,
    lng: 77.0266,
    contactEmail: "ortho@gurgaon-institute.in",
    contactPhone: "+91 124 456 7890",
    rating: 4.8,
    reviewCount: 567,
  }),
  createProvider({
    id: "in-7",
    name: "Kolkata Bariatric Center",
    slug: "kolkata-bariatric-center",
    country: "India",
    city: "Kolkata",
    address: "Park Street, Kolkata 700016",
    description: "Metabolic surgery specialists with comprehensive nutritional support programs.",
    accreditations: ["NABH", "ISO 9001"],
    procedures: ["Gastric Sleeve", "Gastric Bypass"],
    lat: 22.5536,
    lng: 88.351,
    contactEmail: "bariatric@kolkata-center.in",
    contactPhone: "+91 33 2345 6789",
    rating: 4.6,
    reviewCount: 189,
  }),
  createProvider({
    id: "in-8",
    name: "Jaipur Hair Transplant Clinic",
    slug: "jaipur-hair-transplant-clinic",
    country: "India",
    city: "Jaipur",
    address: "C-Scheme, Jaipur, Rajasthan 302001",
    description: "Affordable FUE hair transplants with experienced surgical teams.",
    accreditations: ["ISO 9001"],
    procedures: ["Hair Transplant"],
    lat: 26.9124,
    lng: 75.7873,
    contactEmail: "hair@jaipur-transplant.in",
    contactPhone: "+91 141 234 5678",
    rating: 4.5,
    reviewCount: 312,
  }),
  createProvider({
    id: "in-9",
    name: "Pune Spine & Neuro Center",
    slug: "pune-spine-neuro-center",
    country: "India",
    city: "Pune",
    address: "Senapati Bapat Road, Pune 411016",
    description: "Advanced spine surgery with minimally invasive techniques.",
    accreditations: ["NABH", "ISO 9001"],
    procedures: ["Spine Surgery"],
    lat: 18.5246,
    lng: 73.841,
    contactEmail: "spine@pune-neuro.in",
    contactPhone: "+91 20 2345 6789",
    rating: 4.7,
    reviewCount: 145,
  }),
  createProvider({
    id: "in-10",
    name: "Kochi Cardiac Care Institute",
    slug: "kochi-cardiac-care-institute",
    country: "India",
    city: "Kochi",
    address: "MG Road, Kochi, Kerala 682016",
    description: "Cardiac surgery center with internationally trained cardiothoracic surgeons.",
    accreditations: ["JCI", "NABH"],
    procedures: ["Cardiac Bypass"],
    lat: 9.9312,
    lng: 76.2673,
    contactEmail: "cardiac@kochi-care.in",
    contactPhone: "+91 484 234 5678",
    rating: 4.8,
    reviewCount: 423,
  }),
  createProvider({
    id: "in-11",
    name: "Ahmedabad Breast Surgery Center",
    slug: "ahmedabad-breast-surgery-center",
    country: "India",
    city: "Ahmedabad",
    address: "SG Highway, Ahmedabad, Gujarat 380054",
    description: "Reconstructive and cosmetic breast surgery with compassionate care teams.",
    accreditations: ["NABH", "ISO 9001"],
    procedures: ["Breast Augmentation", "Tummy Tuck"],
    lat: 23.0225,
    lng: 72.5714,
    contactEmail: "breast@ahmedabad-surgery.in",
    contactPhone: "+91 79 2345 6789",
    rating: 4.6,
    reviewCount: 167,
  }),
];
