import { createProvider, pricesFor } from "../factory";

export const mexicoProviders = [
  createProvider({
    id: "mx-1",
    name: "Baja Dental Excellence",
    slug: "baja-dental-excellence",
    country: "Mexico",
    city: "Tijuana",
    address: "Av. Revolución 1234, Zona Centro, Tijuana, Baja California",
    description:
      "Premier dental clinic specializing in implants, veneers, and full-mouth restorations for international patients.",
    accreditations: ["JCI", "ISO 9001", "ADA Member"],
    procedures: ["Dental Implants", "Veneers", "All-on-4"],
    procedurePrices: pricesFor(["Dental Implants", "Veneers", "All-on-4"], {
      "Dental Implants": 890,
      Veneers: 320,
      "All-on-4": 8500,
    }),
    lat: 32.5149,
    lng: -117.0382,
    contactEmail: "info@bajadental.com",
    contactPhone: "+52 664 123 4567",
    rating: 4.9,
    reviewCount: 342,
  }),
  createProvider({
    id: "mx-2",
    name: "Cancún Medical Center",
    slug: "cancun-medical-center",
    country: "Mexico",
    city: "Cancún",
    address: "Blvd. Kukulcan Km 12.5, Zona Hotelera, Cancún",
    description:
      "Full-service hospital offering orthopedic, bariatric, and cosmetic procedures with resort-style recovery packages.",
    accreditations: ["JCI", "CSG-Certified", "ISO 14001"],
    procedures: ["Knee Replacement", "Hip Replacement", "Gastric Sleeve", "Tummy Tuck"],
    procedurePrices: pricesFor(
      ["Knee Replacement", "Hip Replacement", "Gastric Sleeve", "Tummy Tuck"],
      { "Knee Replacement": 12500, "Hip Replacement": 11800, "Gastric Sleeve": 5200, "Tummy Tuck": 4800 }
    ),
    lat: 21.1619,
    lng: -86.8515,
    contactEmail: "contact@cancunmedical.com",
    contactPhone: "+52 998 234 5678",
    rating: 4.8,
    reviewCount: 218,
  }),
  createProvider({
    id: "mx-3",
    name: "Monterrey Cosmetic Institute",
    slug: "monterrey-cosmetic-institute",
    country: "Mexico",
    city: "Monterrey",
    address: "Av. San Pedro 123, San Pedro Garza García, Nuevo León",
    description: "Board-certified plastic surgeons specializing in rhinoplasty and body contouring for medical tourists.",
    accreditations: ["JCI", "ISO 9001"],
    procedures: ["Rhinoplasty", "Liposuction", "Breast Augmentation"],
    procedurePrices: pricesFor(["Rhinoplasty", "Liposuction", "Breast Augmentation"], {
      Rhinoplasty: 3400,
      Liposuction: 2900,
      "Breast Augmentation": 4100,
    }),
    lat: 25.6515,
    lng: -100.3769,
    contactEmail: "info@monterreycosmetic.mx",
    contactPhone: "+52 81 8123 4567",
    rating: 4.7,
    reviewCount: 189,
  }),
  createProvider({
    id: "mx-4",
    name: "Guadalajara Bariatric Specialists",
    slug: "guadalajara-bariatric-specialists",
    country: "Mexico",
    city: "Guadalajara",
    address: "Av. Vallarta 2345, Col. Americana, Guadalajara, Jalisco",
    description: "Dedicated bariatric center with comprehensive pre- and post-operative support for international patients.",
    accreditations: ["CSG-Certified", "ISO 9001"],
    procedures: ["Gastric Sleeve", "Gastric Bypass"],
    lat: 20.6737,
    lng: -103.3444,
    contactEmail: "hello@gdlbariatric.mx",
    contactPhone: "+52 33 3612 7890",
    rating: 4.8,
    reviewCount: 412,
  }),
  createProvider({
    id: "mx-5",
    name: "Playa del Carmen Dental Studio",
    slug: "playa-del-carmen-dental-studio",
    country: "Mexico",
    city: "Playa del Carmen",
    address: "Calle 10 Norte 123, Centro, Playa del Carmen, Quintana Roo",
    description: "Beachside dental clinic popular with North American patients seeking implants and cosmetic dentistry.",
    accreditations: ["ADA Member", "ISO 9001"],
    procedures: ["Dental Implants", "Dental Crowns", "Veneers"],
    lat: 20.6296,
    lng: -87.0739,
    contactEmail: "smile@pdc-dental.mx",
    contactPhone: "+52 984 123 7890",
    rating: 4.9,
    reviewCount: 267,
  }),
  createProvider({
    id: "mx-6",
    name: "Mexico City Fertility Center",
    slug: "mexico-city-fertility-center",
    country: "Mexico",
    city: "Mexico City",
    address: "Av. Insurgentes Sur 1458, Tlalpan, Ciudad de México",
    description: "Modern fertility clinic with high IVF success rates and English-speaking staff.",
    accreditations: ["JCI", "RTAC Accredited"],
    procedures: ["IVF", "Egg Freezing"],
    lat: 19.3019,
    lng: -99.1524,
    contactEmail: "care@mcfertility.mx",
    contactPhone: "+52 55 5432 1098",
    rating: 4.8,
    reviewCount: 534,
  }),
  createProvider({
    id: "mx-7",
    name: "Los Algodones Smile Center",
    slug: "los-algodones-smile-center",
    country: "Mexico",
    city: "Los Algodones",
    address: "Av. A 456, Los Algodones, Baja California",
    description: "High-volume dental destination minutes from the US border, known for affordable implant packages.",
    accreditations: ["ADA Member", "ISO 9001"],
    procedures: ["Dental Implants", "All-on-4", "Dental Crowns"],
    procedurePrices: pricesFor(["Dental Implants", "All-on-4", "Dental Crowns"], {
      "Dental Implants": 750,
      "All-on-4": 7200,
      "Dental Crowns": 380,
    }),
    lat: 32.7136,
    lng: -114.7339,
    contactEmail: "info@algodones-smile.mx",
    contactPhone: "+52 653 123 4567",
    rating: 4.6,
    reviewCount: 891,
  }),
  createProvider({
    id: "mx-8",
    name: "Puerto Vallarta Orthopedic Hospital",
    slug: "puerto-vallarta-orthopedic-hospital",
    country: "Mexico",
    city: "Puerto Vallarta",
    address: "Blvd. Francisco Medina Ascencio 2485, Puerto Vallarta, Jalisco",
    description: "Joint replacement specialists with recovery packages in a resort setting.",
    accreditations: ["JCI", "ISO 14001"],
    procedures: ["Knee Replacement", "Hip Replacement", "ACL Reconstruction"],
    lat: 20.6534,
    lng: -105.2253,
    contactEmail: "ortho@pv-hospital.mx",
    contactPhone: "+52 322 234 5678",
    rating: 4.7,
    reviewCount: 156,
  }),
  createProvider({
    id: "mx-9",
    name: "Rosarito Aesthetic Clinic",
    slug: "rosarito-aesthetic-clinic",
    country: "Mexico",
    city: "Rosarito",
    address: "Blvd. Benito Juárez 890, Rosarito, Baja California",
    description: "Coastal aesthetic clinic offering facelifts and body procedures with hotel recovery partners.",
    accreditations: ["ISO 9001"],
    procedures: ["Facelift", "Tummy Tuck", "Liposuction"],
    lat: 32.3661,
    lng: -117.0619,
    contactEmail: "book@rosarito-aesthetic.mx",
    contactPhone: "+52 661 456 7890",
    rating: 4.5,
    reviewCount: 98,
  }),
  createProvider({
    id: "mx-10",
    name: "Merida LASIK Vision Center",
    slug: "merida-lasik-vision-center",
    country: "Mexico",
    city: "Mérida",
    address: "Calle 60 456, Centro, Mérida, Yucatán",
    description: "Ophthalmology center with advanced LASIK and cataract technology for international patients.",
    accreditations: ["ISO 9001", "AAO Member"],
    procedures: ["LASIK Eye Surgery", "Cataract Surgery"],
    lat: 20.9674,
    lng: -89.5926,
    contactEmail: "vision@merida-lasik.mx",
    contactPhone: "+52 999 234 5678",
    rating: 4.8,
    reviewCount: 203,
  }),
  createProvider({
    id: "mx-11",
    name: "Tijuana Hair Restoration Clinic",
    slug: "tijuana-hair-restoration-clinic",
    country: "Mexico",
    city: "Tijuana",
    address: "Paseo de los Héroes 10289, Zona Río, Tijuana",
    description: "FUE and DHI hair transplant specialists serving cross-border medical tourists.",
    accreditations: ["ISHRS Member", "ISO 9001"],
    procedures: ["Hair Transplant"],
    procedurePrices: [{ name: "FUE Hair Transplant (3000 grafts)", priceUsd: 2100 }],
    lat: 32.5225,
    lng: -117.0139,
    contactEmail: "info@tijuana-hair.mx",
    contactPhone: "+52 664 987 6543",
    rating: 4.7,
    reviewCount: 445,
  }),
];
