import { createProvider } from "../factory";

export const southKoreaProviders = [
  createProvider({
    id: "kr-1",
    name: "Seoul Rhinoplasty Center",
    slug: "seoul-rhinoplasty-center",
    country: "South Korea",
    city: "Seoul",
    address: "Gangnam-daero 123, Gangnam-gu, Seoul",
    description: "Korea's premier rhinoplasty clinic with natural-looking results and 3D simulation.",
    accreditations: ["JCI", "ISO 9001", "Korean Medical Association"],
    procedures: ["Rhinoplasty"],
    procedurePrices: [
      { name: "Rhinoplasty", priceUsd: 3800 },
      { name: "Revision Rhinoplasty", priceUsd: 5200 },
    ],
    lat: 37.4979,
    lng: 127.0276,
    contactEmail: "info@seoul-rhino.kr",
    contactPhone: "+82 2 3456 7890",
    rating: 4.9,
    reviewCount: 1567,
  }),
  createProvider({
    id: "kr-2",
    name: "Gangnam Plastic Surgery Hospital",
    slug: "gangnam-plastic-surgery-hospital",
    country: "South Korea",
    city: "Seoul",
    address: "Apgujeong-ro 456, Gangnam-gu, Seoul",
    description: "Full-service aesthetic hospital in the heart of Gangnam's beauty district.",
    accreditations: ["JCI", "ISO 9001"],
    procedures: ["Rhinoplasty", "Facelift", "Breast Augmentation", "Liposuction"],
    lat: 37.527,
    lng: 127.0286,
    contactEmail: "info@gangnam-plastic.kr",
    contactPhone: "+82 2 4567 8901",
    rating: 4.8,
    reviewCount: 2345,
  }),
  createProvider({
    id: "kr-3",
    name: "Busan Aesthetic Clinic",
    slug: "busan-aesthetic-clinic",
    country: "South Korea",
    city: "Busan",
    address: "Haeundae Beach Road 78, Haeundae-gu, Busan",
    description: "Coastal aesthetic clinic specializing in facial contouring and rhinoplasty.",
    accreditations: ["ISO 9001", "Korean Medical Association"],
    procedures: ["Rhinoplasty", "Facelift", "Liposuction"],
    lat: 35.1587,
    lng: 129.1604,
    contactEmail: "info@busan-aesthetic.kr",
    contactPhone: "+82 51 234 5678",
    rating: 4.7,
    reviewCount: 456,
  }),
  createProvider({
    id: "kr-4",
    name: "Seoul LASIK Vision Institute",
    slug: "seoul-lasik-vision-institute",
    country: "South Korea",
    city: "Seoul",
    address: "Teheran-ro 234, Gangnam-gu, Seoul",
    description: "Advanced SMILE and LASIK procedures with same-day recovery.",
    accreditations: ["JCI", "AAO Member"],
    procedures: ["LASIK Eye Surgery", "Cataract Surgery"],
    lat: 37.5012,
    lng: 127.0396,
    contactEmail: "vision@seoul-lasik.kr",
    contactPhone: "+82 2 5678 9012",
    rating: 4.9,
    reviewCount: 890,
  }),
  createProvider({
    id: "kr-5",
    name: "Seoul Dental Aesthetics",
    slug: "seoul-dental-aesthetics",
    country: "South Korea",
    city: "Seoul",
    address: "Myeongdong 8-gil 12, Jung-gu, Seoul",
    description: "Premium cosmetic dentistry with veneer and implant specialists.",
    accreditations: ["ISO 9001", "Korean Dental Association"],
    procedures: ["Veneers", "Dental Implants", "Dental Crowns"],
    lat: 37.5636,
    lng: 126.9834,
    contactEmail: "dental@seoul-aesthetics.kr",
    contactPhone: "+82 2 6789 0123",
    rating: 4.8,
    reviewCount: 567,
  }),
  createProvider({
    id: "kr-6",
    name: "Seoul Fertility & IVF Center",
    slug: "seoul-fertility-ivf-center",
    country: "South Korea",
    city: "Seoul",
    address: "Yeoksam-dong, Gangnam-gu, Seoul",
    description: "High-tech fertility center with PGT testing and egg freezing programs.",
    accreditations: ["JCI", "ISO 15189"],
    procedures: ["IVF", "Egg Freezing"],
    lat: 37.5006,
    lng: 127.0365,
    contactEmail: "ivf@seoul-fertility.kr",
    contactPhone: "+82 2 7890 1234",
    rating: 4.8,
    reviewCount: 678,
  }),
  createProvider({
    id: "kr-7",
    name: "Incheon Hair Transplant Clinic",
    slug: "incheon-hair-transplant-clinic",
    country: "South Korea",
    city: "Incheon",
    address: "Songdo International City, Incheon",
    description: "Hair restoration clinic near Incheon International Airport for medical tourists.",
    accreditations: ["ISHRS Member", "ISO 9001"],
    procedures: ["Hair Transplant"],
    lat: 37.3827,
    lng: 126.6449,
    contactEmail: "hair@incheon-clinic.kr",
    contactPhone: "+82 32 234 5678",
    rating: 4.6,
    reviewCount: 234,
  }),
  createProvider({
    id: "kr-8",
    name: "Seoul Body Contouring Center",
    slug: "seoul-body-contouring-center",
    country: "South Korea",
    city: "Seoul",
    address: "Sinsa-dong, Gangnam-gu, Seoul",
    description: "Body sculpting experts with liposuction and tummy tuck specialization.",
    accreditations: ["ISO 9001"],
    procedures: ["Liposuction", "Tummy Tuck", "Breast Augmentation"],
    lat: 37.5165,
    lng: 127.0232,
    contactEmail: "body@seoul-contouring.kr",
    contactPhone: "+82 2 8901 2345",
    rating: 4.7,
    reviewCount: 345,
  }),
  createProvider({
    id: "kr-9",
    name: "Seoul Orthopedic Hospital",
    slug: "seoul-orthopedic-hospital",
    country: "South Korea",
    city: "Seoul",
    address: "Nowon-gu, Seoul 139-743",
    description: "Advanced joint replacement with robotic surgery systems.",
    accreditations: ["JCI", "ISO 9001"],
    procedures: ["Knee Replacement", "Hip Replacement", "ACL Reconstruction"],
    lat: 37.6542,
    lng: 127.0568,
    contactEmail: "ortho@seoul-hospital.kr",
    contactPhone: "+82 2 9012 3456",
    rating: 4.8,
    reviewCount: 412,
  }),
  createProvider({
    id: "kr-10",
    name: "Daegu Bariatric Center",
    slug: "daegu-bariatric-center",
    country: "South Korea",
    city: "Daegu",
    address: "Suseong-gu, Daegu 421-740",
    description: "Metabolic surgery center with comprehensive lifestyle coaching.",
    accreditations: ["ISO 9001", "Korean Medical Association"],
    procedures: ["Gastric Sleeve", "Gastric Bypass"],
    lat: 35.8714,
    lng: 128.6014,
    contactEmail: "bariatric@daegu-center.kr",
    contactPhone: "+82 53 234 5678",
    rating: 4.6,
    reviewCount: 178,
  }),
];
