import { createProvider, pricesFor } from "../factory";

export const thailandProviders = [
  createProvider({
    id: "th-1",
    name: "Bangkok Fertility Institute",
    slug: "bangkok-fertility-institute",
    country: "Thailand",
    city: "Bangkok",
    address: "88 Sukhumvit Road, Watthana, Bangkok 10110",
    description: "Leading fertility center with world-class IVF success rates and personalized treatment plans.",
    accreditations: ["JCI", "RTAC Accredited", "ISO 15189"],
    procedures: ["IVF", "Egg Freezing"],
    procedurePrices: pricesFor(["IVF", "Egg Freezing"], { IVF: 6500, "Egg Freezing": 3200 }),
    lat: 13.7563,
    lng: 100.5018,
    contactEmail: "hello@bangkokfertility.th",
    contactPhone: "+66 2 123 4567",
    rating: 4.9,
    reviewCount: 567,
  }),
  createProvider({
    id: "th-2",
    name: "Phuket International Hospital",
    slug: "phuket-international-hospital",
    country: "Thailand",
    city: "Phuket",
    address: "44 Chalermprakiat Ror 9 Rd, Mueang Phuket District",
    description: "Accredited multi-specialty hospital popular with medical tourists seeking orthopedic and cosmetic procedures.",
    accreditations: ["JCI", "HA Thailand", "ISO 9001"],
    procedures: ["Knee Replacement", "Hip Replacement", "Rhinoplasty", "LASIK Eye Surgery"],
    procedurePrices: pricesFor(
      ["Knee Replacement", "Hip Replacement", "Rhinoplasty", "LASIK Eye Surgery"],
      { "Knee Replacement": 9800, "Hip Replacement": 9200, Rhinoplasty: 3500, "LASIK Eye Surgery": 2200 }
    ),
    lat: 7.8804,
    lng: 98.3923,
    contactEmail: "info@phukethospital.th",
    contactPhone: "+66 76 234 5678",
    rating: 4.7,
    reviewCount: 891,
  }),
  createProvider({
    id: "th-3",
    name: "Bangkok Cosmetic Surgery Center",
    slug: "bangkok-cosmetic-surgery-center",
    country: "Thailand",
    city: "Bangkok",
    address: "2 Sukhumvit Soi 31, Watthana, Bangkok",
    description: "Premium aesthetic surgery center specializing in facial and body contouring procedures.",
    accreditations: ["JCI", "ISO 9001"],
    procedures: ["Rhinoplasty", "Facelift", "Breast Augmentation", "Liposuction"],
    lat: 13.7398,
    lng: 100.5599,
    contactEmail: "info@bangkokcosmetic.th",
    contactPhone: "+66 2 234 5678",
    rating: 4.8,
    reviewCount: 723,
  }),
  createProvider({
    id: "th-4",
    name: "Chiang Mai Dental Clinic",
    slug: "chiang-mai-dental-clinic",
    country: "Thailand",
    city: "Chiang Mai",
    address: "123 Nimmanhaemin Road, Suthep, Chiang Mai",
    description: "Award-winning dental clinic in northern Thailand with implant and veneer specialists.",
    accreditations: ["ISO 9001", "ADA Member"],
    procedures: ["Dental Implants", "Veneers", "Dental Crowns"],
    lat: 18.7961,
    lng: 98.9793,
    contactEmail: "smile@chiangmai-dental.th",
    contactPhone: "+66 53 234 5678",
    rating: 4.9,
    reviewCount: 312,
  }),
  createProvider({
    id: "th-5",
    name: "Samitivej Hospital Bangkok",
    slug: "samitivej-hospital-bangkok",
    country: "Thailand",
    city: "Bangkok",
    address: "133 Sukhumvit 49, Khlong Tan Nuea, Bangkok",
    description: "International hospital with comprehensive cardiac and orthopedic programs.",
    accreditations: ["JCI", "HA Thailand"],
    procedures: ["Cardiac Bypass", "Knee Replacement", "Spine Surgery"],
    lat: 13.7356,
    lng: 100.5692,
    contactEmail: "international@samitivej.th",
    contactPhone: "+66 2 711 8000",
    rating: 4.8,
    reviewCount: 1456,
  }),
  createProvider({
    id: "th-6",
    name: "Pattaya Bariatric Center",
    slug: "pattaya-bariatric-center",
    country: "Thailand",
    city: "Pattaya",
    address: "456 Beach Road, Pattaya, Chonburi",
    description: "Weight-loss surgery specialists with beachside recovery facilities.",
    accreditations: ["ISO 9001", "HA Thailand"],
    procedures: ["Gastric Sleeve", "Gastric Bypass"],
    lat: 12.9236,
    lng: 100.8825,
    contactEmail: "info@pattaya-bariatric.th",
    contactPhone: "+66 38 234 5678",
    rating: 4.6,
    reviewCount: 234,
  }),
  createProvider({
    id: "th-7",
    name: "Bangkok Hair Transplant Clinic",
    slug: "bangkok-hair-transplant-clinic",
    country: "Thailand",
    city: "Bangkok",
    address: "789 Rama IV Road, Silom, Bangkok",
    description: "FUE and DHI hair restoration with all-inclusive packages for international clients.",
    accreditations: ["ISHRS Member", "ISO 9001"],
    procedures: ["Hair Transplant"],
    lat: 13.7263,
    lng: 100.5234,
    contactEmail: "hair@bangkok-transplant.th",
    contactPhone: "+66 2 345 6789",
    rating: 4.7,
    reviewCount: 567,
  }),
  createProvider({
    id: "th-8",
    name: "Phuket LASIK Center",
    slug: "phuket-lasik-center",
    country: "Thailand",
    city: "Phuket",
    address: "89/1 Rat-U-Thit Road, Patong, Phuket",
    description: "Dedicated eye surgery center with SMILE and LASIK for medical tourists.",
    accreditations: ["ISO 9001", "AAO Member"],
    procedures: ["LASIK Eye Surgery", "Cataract Surgery"],
    lat: 7.8965,
    lng: 98.2963,
    contactEmail: "vision@phuket-lasik.th",
    contactPhone: "+66 76 345 6789",
    rating: 4.8,
    reviewCount: 189,
  }),
  createProvider({
    id: "th-9",
    name: "Bangkok Spine Institute",
    slug: "bangkok-spine-institute",
    country: "Thailand",
    city: "Bangkok",
    address: "55 Petchaburi Road, Ratchathewi, Bangkok",
    description: "Minimally invasive spine surgery center with international patient coordinators.",
    accreditations: ["JCI", "ISO 9001"],
    procedures: ["Spine Surgery", "ACL Reconstruction"],
    lat: 13.7563,
    lng: 100.5347,
    contactEmail: "spine@bangkok-institute.th",
    contactPhone: "+66 2 456 7890",
    rating: 4.7,
    reviewCount: 278,
  }),
  createProvider({
    id: "th-10",
    name: "Hua Hin Dental & Wellness",
    slug: "hua-hin-dental-wellness",
    country: "Thailand",
    city: "Hua Hin",
    address: "123 Petchkasem Road, Hua Hin, Prachuap Khiri Khan",
    description: "Resort-town dental clinic combining implants with wellness recovery packages.",
    accreditations: ["ISO 9001"],
    procedures: ["Dental Implants", "All-on-4", "Veneers"],
    lat: 12.5684,
    lng: 99.9577,
    contactEmail: "wellness@huahin-dental.th",
    contactPhone: "+66 32 234 5678",
    rating: 4.8,
    reviewCount: 145,
  }),
  createProvider({
    id: "th-11",
    name: "Bangkok Tummy Tuck Specialists",
    slug: "bangkok-tummy-tuck-specialists",
    country: "Thailand",
    city: "Bangkok",
    address: "34 Soi Thonglor 13, Watthana, Bangkok",
    description: "Body contouring experts specializing in post-weight-loss reconstruction.",
    accreditations: ["ISO 9001"],
    procedures: ["Tummy Tuck", "Liposuction", "Breast Augmentation"],
    lat: 13.7317,
    lng: 100.5811,
    contactEmail: "body@bangkok-contour.th",
    contactPhone: "+66 2 567 8901",
    rating: 4.6,
    reviewCount: 198,
  }),
];
