import { createProvider, pricesFor } from "../factory";

export const turkeyProviders = [
  createProvider({
    id: "tr-1",
    name: "Istanbul Hair & Aesthetics",
    slug: "istanbul-hair-aesthetics",
    country: "Turkey",
    city: "Istanbul",
    address: "Nişantaşı, Teşvikiye Cd. No: 45, Şişli, Istanbul",
    description: "Turkey's top destination for hair transplants and rhinoplasty with luxury recovery hotels.",
    accreditations: ["JCI", "ISHRS Member", "ISO 9001"],
    procedures: ["Hair Transplant", "Rhinoplasty", "Facelift"],
    procedurePrices: pricesFor(["Hair Transplant", "Rhinoplasty", "Facelift"], {
      "Hair Transplant": 2200,
      Rhinoplasty: 3200,
      Facelift: 4500,
    }),
    lat: 41.0488,
    lng: 28.9955,
    contactEmail: "info@istanbulhair.tr",
    contactPhone: "+90 212 345 6789",
    rating: 4.8,
    reviewCount: 2104,
  }),
  createProvider({
    id: "tr-2",
    name: "Ankara Orthopedic Specialists",
    slug: "ankara-orthopedic-specialists",
    country: "Turkey",
    city: "Ankara",
    address: "Bilkent Plaza B1 Blok, Bilkent, Çankaya, Ankara",
    description: "Robotic-assisted joint replacement and spine surgery programs.",
    accreditations: ["JCI", "TEMOS", "ISO 15189"],
    procedures: ["Knee Replacement", "Hip Replacement", "Spine Surgery", "ACL Reconstruction"],
    lat: 39.8719,
    lng: 32.7473,
    contactEmail: "ortho@ankaraspecialists.tr",
    contactPhone: "+90 312 456 7890",
    rating: 4.7,
    reviewCount: 389,
  }),
  createProvider({
    id: "tr-3",
    name: "Istanbul Rhinoplasty Center",
    slug: "istanbul-rhinoplasty-center",
    country: "Turkey",
    city: "Istanbul",
    address: "Bağdat Caddesi 234, Kadıköy, Istanbul",
    description: "Dedicated rhinoplasty clinic with revision specialists and 3D imaging consultation.",
    accreditations: ["JCI", "ISO 9001"],
    procedures: ["Rhinoplasty"],
    procedurePrices: [
      { name: "Rhinoplasty", priceUsd: 2900 },
      { name: "Revision Rhinoplasty", priceUsd: 3800 },
    ],
    lat: 40.9634,
    lng: 29.0634,
    contactEmail: "nose@istanbul-rhino.tr",
    contactPhone: "+90 216 345 6789",
    rating: 4.9,
    reviewCount: 876,
  }),
  createProvider({
    id: "tr-4",
    name: "Antalya Dental Tourism Clinic",
    slug: "antalya-dental-tourism-clinic",
    country: "Turkey",
    city: "Antalya",
    address: "Lara Caddesi 456, Muratpaşa, Antalya",
    description: "Mediterranean dental clinic combining holidays with implant and veneer treatments.",
    accreditations: ["ISO 9001", "TEMOS"],
    procedures: ["Dental Implants", "Veneers", "All-on-4"],
    lat: 36.8841,
    lng: 30.7056,
    contactEmail: "dental@antalya-tourism.tr",
    contactPhone: "+90 242 234 5678",
    rating: 4.8,
    reviewCount: 445,
  }),
  createProvider({
    id: "tr-5",
    name: "Izmir Bariatric Hospital",
    slug: "izmir-bariatric-hospital",
    country: "Turkey",
    city: "Izmir",
    address: "Alsancak, Izmir 35220",
    description: "Comprehensive weight-loss surgery with multilingual patient support.",
    accreditations: ["JCI", "ISO 9001"],
    procedures: ["Gastric Sleeve", "Gastric Bypass"],
    lat: 38.4237,
    lng: 27.1428,
    contactEmail: "bariatric@izmir-hospital.tr",
    contactPhone: "+90 232 345 6789",
    rating: 4.7,
    reviewCount: 312,
  }),
  createProvider({
    id: "tr-6",
    name: "Istanbul Vision LASIK Center",
    slug: "istanbul-vision-lasik-center",
    country: "Turkey",
    city: "Istanbul",
    address: "Levent Mahallesi, Büyükdere Cd., Istanbul",
    description: "Premium eye surgery center with femtosecond LASIK technology.",
    accreditations: ["ISO 9001", "AAO Member"],
    procedures: ["LASIK Eye Surgery", "Cataract Surgery"],
    lat: 41.0819,
    lng: 29.011,
    contactEmail: "vision@istanbul-lasik.tr",
    contactPhone: "+90 212 567 8901",
    rating: 4.8,
    reviewCount: 534,
  }),
  createProvider({
    id: "tr-7",
    name: "Bursa Cosmetic Surgery Clinic",
    slug: "bursa-cosmetic-surgery-clinic",
    country: "Turkey",
    city: "Bursa",
    address: "Atatürk Caddesi 78, Osmangazi, Bursa",
    description: "Affordable body contouring and breast surgery near Istanbul.",
    accreditations: ["ISO 9001"],
    procedures: ["Breast Augmentation", "Tummy Tuck", "Liposuction"],
    lat: 40.1885,
    lng: 29.061,
    contactEmail: "cosmetic@bursa-clinic.tr",
    contactPhone: "+90 224 234 5678",
    rating: 4.6,
    reviewCount: 198,
  }),
  createProvider({
    id: "tr-8",
    name: "Istanbul Fertility Institute",
    slug: "istanbul-fertility-institute",
    country: "Turkey",
    city: "Istanbul",
    address: "Etiler, Nispetiye Cd., Beşiktaş, Istanbul",
    description: "Modern IVF clinic with donor programs and genetic screening.",
    accreditations: ["JCI", "ISO 15189"],
    procedures: ["IVF", "Egg Freezing"],
    lat: 41.0766,
    lng: 29.0233,
    contactEmail: "fertility@istanbul-institute.tr",
    contactPhone: "+90 212 678 9012",
    rating: 4.8,
    reviewCount: 423,
  }),
  createProvider({
    id: "tr-9",
    name: "Bodrum Aesthetic Retreat",
    slug: "bodrum-aesthetic-retreat",
    country: "Turkey",
    city: "Bodrum",
    address: "Yalıkavak Marina, Bodrum, Muğla",
    description: "Boutique aesthetic clinic with seaside recovery villas.",
    accreditations: ["ISO 9001", "TEMOS"],
    procedures: ["Rhinoplasty", "Facelift", "Liposuction"],
    lat: 37.1042,
    lng: 27.267,
    contactEmail: "retreat@bodrum-aesthetic.tr",
    contactPhone: "+90 252 345 6789",
    rating: 4.7,
    reviewCount: 156,
  }),
  createProvider({
    id: "tr-10",
    name: "Trabzon Hair Clinic",
    slug: "trabzon-hair-clinic",
    country: "Turkey",
    city: "Trabzon",
    address: "Atatürk Alanı 12, Ortahisar, Trabzon",
    description: "High-volume FUE clinic with competitive pricing and airport transfers.",
    accreditations: ["ISHRS Member"],
    procedures: ["Hair Transplant"],
    lat: 41.0027,
    lng: 39.7168,
    contactEmail: "hair@trabzon-clinic.tr",
    contactPhone: "+90 462 234 5678",
    rating: 4.5,
    reviewCount: 678,
  }),
  createProvider({
    id: "tr-11",
    name: "Istanbul Tummy Tuck Specialists",
    slug: "istanbul-tummy-tuck-specialists",
    country: "Turkey",
    city: "Istanbul",
    address: "Fulya Mahallesi, Büyükdere Cd., Şişli, Istanbul",
    description: "Post-bariatric body reconstruction and abdominoplasty experts.",
    accreditations: ["JCI", "ISO 9001"],
    procedures: ["Tummy Tuck", "Liposuction", "Breast Augmentation"],
    lat: 41.0553,
    lng: 28.9987,
    contactEmail: "body@istanbul-tummy.tr",
    contactPhone: "+90 212 789 0123",
    rating: 4.7,
    reviewCount: 289,
  }),
];
